### ISSUE TITLE
No API key

### ISSUE THREAD

**Issue by s1mahoeg** [icfpcontest2020/dockerfiles#51]
Hi,

yesterday I've registered for the contest successfully and already did some stuff to get familiar with the submission system. But I cannot log in again. I'm getting asked for an API key which I do not have. I checked my Emails but I did not receive any Email from the ICFP contest organizers.

To whom can I reach out in this regard?

**Comment by igorlukanin** [comment]
Hi. Thanks for reaching out!

As of this moment, we don't send any emails after registration. That's why we advice to keep the API key which is available after registration on the _Team profile_ page: https://icfpcontest2020.github.io/#/team

What is your team name? I will send your API key to the email provided for that team. You may post the team name here or send it to me@igorlukanin.io.

**Comment by s1mahoeg** [comment]
Oh, I guess I missed that note. Sorry for the inconvenience!

My team name is "sudo rm -rf /"

Thanks for your help!

**Comment by igorlukanin** [comment]
Sent the email. Feel free to reopen this issue if you can't log in into your profile.
