### ISSUE TITLE
Python dependency management

### ISSUE THREAD

**Issue by tilsche** [icfpcontest2020/dockerfiles#67]
My team is a bit concerned about how dependencies for Python are handled. I understand the advertised process is to make a PR for the `python` platform to add to the `requirements.txt`. But we don't know which libraries are needed before hand, we actually often learn new libraries during the contest. How is this going to scale for a large number of teams and vast number of possible python libraries? How could version conflicts be handled?

I understand an ad-hoc installation of custom `requirements.txt`, or even better with a proper setuptools `setup.py` wont work due lack of internet connectivity.

What's the way out here? I could envision having ready-made `site-packages` folders in the submission branch, e.g. taken from a virtualenv, but I'm not sure about the limitations of portability.

**Comment by beevee** [comment]
Knowing the nature of the task, we think that you probably won't require many third-party libraries.

There are indeed two options to include dependencies:

1. Make PRs to this repo. I'm sure we'll figure out a way to avoid conflicts, at least for 72 hours of development.
2. Include your requirements in any way possible into your submission. Use `virtualenv`, include source files directly, do what you have to do. You can see the base image, so you should be able to include appropriate libraries for the platform. We won't use any obscure platforms to run your code, I can promise.

Please, understand that you won't have to solve any platform-specific or low-level system tasks. You won't be required to parse protobufs or connect to databases. Nothing like that.

**Comment by jmerle** [comment]
[PyInstaller](https://www.pyinstaller.org/) may be helpful here. It builds Python code into a binary and places shared objects of all dependencies alongside the binary and loads those in at runtime. This way you don't have to fiddle with `virtualenv` or `site-packages` and can simply push the binary and the shared objects to the `submission` branch.

A downside to this is that the binaries are OS-specific, so if you build on Windows you get Windows binaries. To get around this you can set up a GitHub Actions workflow (or a pipeline/workflow in your preferred CI environment) to build the source code on the correct OS (the Python platform seems to use Debian Buster) and to automatically push the generated binary and shared objects to the submission branch.

I have done the same thing for my Kotlin project because I use Gradle to pull in some logging dependencies. If you want to you can use my [.github/workflows/build.yml](https://gist.github.com/jmerle/3187803778f7b6bd112b13ddb77441da) file as a starting point and adapt it to work with Python and PyInstaller.

**Comment by tilsche** [comment]
I've been successful with using wheels. I think that's a bit more elegant than Pyinstaller.

Preparation is just

    pip wheel --wheel-dir wheels .

And `install.sh`

    pip install --no-index --find-links ./wheels name-of-our-package

Seems to work just fine with a proper `setup.py`. I used `[console_scripts]` and those were installed and executed by `run.sh` just fine.

Of course the wheels directory has to be in the submissions git. Note that on GitHub, max file size is 100 MiB. Tensorflow has a 500 MiB package. So there are some limitations.
