### ISSUE TITLE
Submissions: empty test logs

### ISSUE THREAD

**Issue by variar** [icfpcontest2020/dockerfiles#73]
What I've done:
- [*] created a private Git repository
- [*] copied the deploy key and added it to the repository
- [*] created a branch called `submission`
- [*] downloaded a starter kit
- [*] modified, committed and pushed the starter kit
- [*] waited for more than 10 minutes

Here's the problem:
Submission builds fine, but tests failed. Test logs are empty, so there is no way to diagnose error

**Comment by beevee** [comment]
Can you tell me your team name please?

**Comment by igorlukanin** [comment]
@beevee I believe it's _Olympia_.

**Comment by variar** [comment]
> Can you tell me your team name please?

Yes, it's Olympia.

**Comment by spaceorc** [comment]
Test Logs is your programs' output (stdout or stderr). It is empty because your code wrote nothing.
Test is failed because your program should make POST request to the url from args[0] and pass args[1] as plain text in body. If our test server won't receive this within 10 seconds test will fail.

Your program crashes with exit code 1
```
root@f41f55066d87:/solution# ./run.sh "http://example.com:80" 123345
root@f41f55066d87:/solution# echo $?
1
```

If you want to see exit code in Test Logs, you can change your run.sh and write exit code to stdout like starterkit does:
```
#!/bin/sh
cd build/output
exec ./solver_executor "$@" || echo "run error code: $?" 
```

**Comment by variar** [comment]
Oops, my bad. Enabled logs to file by default. Seems ok now. Thanks.
